export const BUZZWORDS = [
  "rockstar",
  "ninja",
  "guru",
  "world class",
  "fast-paced",
  "dynamic environment",
  "best-in-class",
  "cutting-edge",
  "game-changer",
  "thought leader",
  "synergy",
  "wear many hats",
];

export const FILLER_PHRASES = [
  "other duties as assigned",
  "etc.",
  "and more",
  "various tasks",
  "as needed",
  "multiple priorities",
  "strong communication skills",
  "team player",
  "self-starter",
  "must be passionate",
];

export const ACTION_VERBS = [
  "build",
  "design",
  "lead",
  "ship",
  "analyze",
  "support",
  "collaborate",
  "own",
  "manage",
  "improve",
  "deliver",
  "coordinate",
  "develop",
  "execute",
  "partner",
];

export const LEADERSHIP_VERBS = [
  "lead",
  "manage",
  "mentor",
  "own strategy",
  "set vision",
  "drive roadmap",
  "oversee",
  "direct",
];

export const TECH_SKILLS = [
  "python",
  "java",
  "javascript",
  "typescript",
  "react",
  "next.js",
  "node",
  "sql",
  "aws",
  "azure",
  "gcp",
  "docker",
  "kubernetes",
  "terraform",
  "graphql",
  "rest",
  "figma",
  "sketch",
  "framer",
  "tableau",
  "power bi",
  "excel",
  "salesforce",
  "hubspot",
  "snowflake",
  "dbt",
  "airflow",
  "spark",
  "pandas",
  "numpy",
  "c++",
  "go",
  "rust",
  "swift",
  "kotlin",
  "android",
  "ios",
  "postgres",
  "mysql",
  "redis",
  "linux",
  "git",
  "jira",
  "notion",
  "photoshop",
  "illustrator",
  "after effects",
  "seo",
  "sem",
  "ga4",
  "google analytics",
];

export const RESPONSIBILITY_HEADINGS = [
  "responsibilities",
  "what you'll do",
  "what you will do",
  "day to day",
  "role overview",
  "you will",
];

export const QUALIFICATION_HEADINGS = [
  "requirements",
  "qualifications",
  "what we're looking for",
  "you have",
  "must have",
];

export const PREFERRED_HEADINGS = [
  "preferred qualifications",
  "nice to have",
  "bonus points",
  "preferred",
];
